version: "3"
services:
  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: mongo:4.4
    container_name: mongo
    ports:
        - $MONGO_HOST_PORT:27017